### ISSUE TITLE
File not found or 403 error

### ISSUE THREAD

**Issue by doogalbear** [petrk94/ownhealthrecord#1]
Found this posted on Reddit and looked interesting. I'm running into these errors at the moment:
File not found and 403 File forbidden

I am installing this on a RPI 3 with a LEMP Stack, PHP 7, and MYSQL. Followed the Readme. 
Will this run under a subdomain?
Do you have an example of an NGINX conf?

It's probably something simple I'm missing, but any help would be appreciated.

**Comment by petrk94** [comment]
Hello @doogalbear 
Im currently updating the application with account functionality. The master branch is currently not usable, please use the release version.
I have it running successfully on a subdomain. There is no problem, its working on a shared host, everything above should not be problem :)

As requirement is LAMP, not LEMP. I have no experience with NGINX, so probably I can not help you here. If you like, you can provide a pull request for this, if you get it running.
As written in the README, its a very young alpha project, so its not stable for working

**Comment by doogalbear** [comment]
Hello @petrk94, 
I got ownhealthrecord running, but cannot get past the registration page. What am I missing?

**Comment by petrk94** [comment]
@doogalbear can you send me a screenshot?
If you have created the mysql database and uploaded everything correctly, you open the index.php file, this is asking for you to login, but thats not possible, due no account exist. You have to register/signup. If you made this step you get a sucessfully message, than you go back to the login page and you can login with the credentials you have used for the account signup. This should work.

**Comment by doogalbear** [comment]
My error. I didn't have the DB setup properly. I was missing two tables. Now after successful login, I get Database error: cannot prepare statement

**Comment by petrk94** [comment]
@doogalbear 
I would recommend you to get a new start with v0.2_alpha.
This version avoid the problem with the database. Just import the database.sql file in https://github.com/petrk94/ownhealthrecord/releases/tag/v0.2-alpha
than you should not get problems to run it.

I will write a install tutorial in the wiki from now on. Its even possible that there are other problems, due I dont know your server configuration

**Comment by petrk94** [comment]
@doogalbear 
Here are the install instruction, this works for me.
https://github.com/petrk94/ownhealthrecord/wiki/Installation-Instruction
If you still get a problem, let me know :)

**Comment by doogalbear** [comment]
Thank you for the instruction page. Sadly, it only verified what I had been doing. Keep the page up for others.  
I started over anyway and step by step got the same error. **Database error: cannot prepare statement** 
Maybe this wasn't meant for a LEMP stack. 
I'll wait for a more stable release or if you're willing to help, let me know what to send.

**Comment by petrk94** [comment]
@doogalbear 
Thats weird, I dont believe that belong to the LEMP stack. If you can open any php file in browser and you have a working server, than there is nothing special necessary.
At which point you get this error message displayed?
Can you send me a screenshot and what is shown in the URL bar?
Was the import of the database.sql file via phpmyadmin to the mysql database successfully? Could you see the tables which got created?

For a future release I can think about that the installer is creating the tables automatically.

**Comment by doogalbear** [comment]
the error message appears right after clicking Login

![petrkscreen1](https://user-images.githubusercontent.com/10004086/46897037-67db5b00-ce4e-11e8-9241-156e4fe34a7f.png)

Yes. the database was successful. 
I see the following tables:
![petrkscreen2](https://user-images.githubusercontent.com/10004086/46897046-775aa400-ce4e-11e8-8e60-4a4309187e6f.png)

**Comment by petrk94** [comment]
@doogalbear 
Thanks for sharing the screenshot. I got it now, the "bug" was on my side. I forgot one table for the structure. Which cause this problem. I will prepare a database fix. Delete the database, create a new one and import the fixed database.sql. Than it should work :)
![missing table](https://user-images.githubusercontent.com/19719052/46906075-007ce400-cefe-11e8-8b58-84b7052d2fa9.PNG)

**Comment by doogalbear** [comment]
@petrk94 
Thank you for the database fix. I can now login and see dashboard. 
I'll let you know if I have any more issues. 

Thank you for all your help.

**Comment by petrk94** [comment]
@doogalbear 
You are welcome :)

**Comment by doogalbear** [comment]
I like the layout and see it has potential. I saw you're working on the functionality. I have noticed that the save buttons don't work yet on Medical Record, Doctor, and Medicine. 
I get "This page isn’t working" on each. 
Keep it up. I'm sure this will be real useful than keeping up with a binder full of forms, once the doctors accept digital formats. My binder has 100 + pages

**Comment by petrk94** [comment]
Thank you :)
Yes, this bug is still in the release v0.2_alpha. In the current branch its already fixed, its just a broken link, you can fix this even manually in each file. Or you just move the files in medical folder into the root application folder where the index.php is located, than this will work too.
The buttons should work^^

**Comment by petrk94** [comment]
@doogalbear 
Today I got in contact with a doctor from germany who seems to be interested, maybe he can give some more information for functions. The fundamental is, this software has to be patient friendly, what I see sometimes at my doctor visits, the software is gross, horrible and I can not imagine, how doctors want/can work with it productive.

> Keep it up. I'm sure this will be real useful than keeping up with a binder full of forms, once the >doctors accept digital formats. My binder has 100 + pages

This is even a special point, I hope to find someone who could help to write a import functionality, so you just need the doctor medical record file and import it in your own system.

What I even noticed, its not yet ready for production, due I could access in theory your own hosting, due there is no user signup verification. I have to look how to make this secure.

**Comment by doogalbear** [comment]
>  what I see sometimes at my doctor visits, the software is gross

This is true. Actually makes one of my doctors unorganized. 

Currently, what I do is compile PDFs (markdown, word, and PDF reports) with bookmarks and host them on Nextcloud for my use and print them for the doctors (those not digitally inclined) A simple page with important info would be helpful. Such as an AIO (all in one) page. Sometimes an AIO can expand to more than 1 page. If you can make this with a font that is still readable and fit on 1 page (front/back) that would be awesome.  

Here's an example of what I use for my AIO.
[Example.pdf](https://github.com/petrk94/ownhealthrecord/files/2475562/Example.pdf)
Here's an updated AIO
[Example2.pdf](https://github.com/petrk94/ownhealthrecord/files/2475579/Example2.pdf)

**Comment by petrk94** [comment]
As I see, this would be worth a own software for.
An Export as html code on one page would not be a problem, but this were too much time consuming for the moment, due its out of my focus for now. You can open it as a separate issue and I will add the enhancement flag for a future release :)
