### ISSUE TITLE
Have you looked into Fully-Homomorphic-Encryption?

### ISSUE THREAD

**Issue by Leopere** [petrk94/ownhealthrecord#11]
Read number 1
https://paragonie.com/blog/2019/01/ciphersweet-searchable-encryption-doesn-t-have-be-bitter
Read number 2
https://blog.cryptographyengineering.com/2012/01/02/very-casual-introduction-to-fully/

Source Code that claims to be FHE 
https://github.com/paragonie/ciphersweet

**Comment by Leopere** [comment]
This would be a way where you could securely store health records while encrypted by default in the database and yet remain searchable.

**Comment by petrk94** [comment]
I dont understand what you mean with searchable? The data which you save in the web application, are plain text and get encrypted via php in the processing part, after its encrypted, the encrypted data are stored in the database. If you open the web application, the data get loaded by decrypting it.

If you want to search it inside of the database, than sorry, but this is not a good idea, if the database get hacked, the data are visible for everyone and this is not the target. If someone break into the database, you can be sure, that it cant be decrypted and you have less to worry about.

**Comment by Leopere** [comment]
This type of encryption was specifically designed for cases like this but okay.

**Comment by petrk94** [comment]
I will keep it in mind, but would make it more complicated and than even with further database models, it would get mess

**Comment by Leopere** [comment]
Hey no big deal it's not easily accessible yet it only has a PHP Library
currently anyways just seems like a good idea to learn about.
