### ISSUE TITLE
Feature Request - Sqlite support

### ISSUE THREAD

**Issue by OliverParoczai** [petrk94/ownhealthrecord#3]
It would be useful to have Sqlite support for smaller deployments where a Mysql server is not that needed.

**Comment by petrk94** [comment]
@Olika120 noted ;) I will take a look how to realize

**Comment by petrk94** [comment]
@Olika120 
Due lack of time, I hope someone can write there some code for it, due I can not get deeper in it through my other projects and work. I want to keep it running for the moment with mysql and take more care about to get it run secure.
