### ISSUE TITLE
Question - install without phpmyadmin

### ISSUE THREAD

**Issue by budbay** [petrk94/ownhealthrecord#4]
Would it be possible to include instructions on how to install without using phpmyadmin?  I've been looking for a project like this and would love to try it however I don't have phpmyadmin on my system(Ubuntu w/LAMP).  Is there a way to use command line instead? Thanks.

**Comment by pedrosousa13** [comment]
@budbay do you have access to your mysql via command line? if so, use this:
`mysql -u username -p database_name < database-structure.sql`
Otherwise you can use something like sequel pro and connect it to your mysql server (local or otherwise). There you can simply import with the top menus.

**Comment by budbay** [comment]
@pedrosousa13 yes I have access through command line, I will try the command as soon as I get time and report back. Thank you for the quick reply.

**Comment by budbay** [comment]
@pedrosousa13 that worked, I'm up and running.  Thank you for your help. Feel free to close this issue.  I don't want to hijack your project any further but LDAP support would be an awesome addition for those of us self hosting a lot of projects.  Anyway thanks again, I look forward to see how this project develops, keep up the good work.

**Comment by petrk94** [comment]
@pedrosousa13  Thank you for helping :) 
@budbay thanks for your request, in future it will be made by a installer, so there will be nothing more to handle manually. LDAP is currently not planned, due its really heavy and I dont have any experience with it. I can imagine to integrate it as a plugin in future, but not as native functionality.

You are welcome, the plan is to release every weekend a new version with small improvements, check out the DeveloperLog where I will update about small changes before releasing it.
