### ISSUE TITLE
Installer doesn't change username/password

### ISSUE THREAD

**Issue by manawenuz** [petrk94/ownhealthrecord#5]
Hello there, I've tried installing ohr on RHEL 8, php 7.2 mariadb 10.3.10, and ran into an issue in which the installer didn't change the default username/password for the database, and hence didn't import the database creation sql file, also it didn't return errors !
I've fixed it by manually editing `includes/psl-config.php` and importing `database_structure.sql` into the database, in case you don't have the time to fix the installer, i believe creating an installation readme would be useful.

**Comment by petrk94** [comment]
Hello @manawenuz 
I can explain you it. The problem is, the installer is making only the psl-config.php, not installing the database ;) 
You have to make it manually, the github repo is a developer branch, if you want a working system, use always the released ones.

**Comment by manawenuz** [comment]
the thing was that the username/password was incorrect in `psl-config` and i had to manually edit it, sorry didn't notice the releases there :-)
