### ISSUE TITLE
Feature Request - Supplement mangement

### ISSUE THREAD

**Issue by manawenuz** [petrk94/ownhealthrecord#6]
Thanks for the project, I think it'd be useful to also add supplements that are being taken.
thanks.

**Comment by petrk94** [comment]
Can you explain the reason why it has to be in a medical record?
I can even take supplements, but doesnt tell my doctor about it to write it in the medical record. Therefore in the future we can take a look about a plugin, but not a function by default.

**Comment by manawenuz** [comment]
the reason for that is that, a simple silly supplement could cause allergies or even worse (kidney stones, horrible reactions), so i prefer to add it to.

**Comment by petrk94** [comment]
For the moment I dont see it as urgent, if there are come more upvotes on this issue, I will think about to add it on the Roadmap.

**Comment by Leopere** [comment]
Sometimes supplementation is important to disclose to a MD for drug interactions.  For example if you take certain mushroom based homeopathic supplements along with chemotherapy drugs you might end up blocking your liver/kidneys from processing the chemotherapy drugs.  If you record these details it might be helpful when you go attend a physician or others.

**Comment by petrk94** [comment]
I will think about it again. I would like to make it, but its taking time, so here must be more people interested in it. Otherwise, you can make a draft how the styling would look like and send a PR, than we can continue talk about integration :)

**Comment by Leopere** [comment]
Of course I'm just giving context to my point of view on it.  I was thinking it could be really beneficial to have something that tracks more than just records the doc sends you because then it could be a point of reference for Emergency room situations when you're out of your usual medical support network.  ( traveling etc )

**Comment by petrk94** [comment]
Welly that's another point, and this will be maybe in future possible, but for the moment, there is no offline version in plan. In a later release where SQLite Will be integrated, it would be possible, but than it need an Android app or whatever and this make it more complicated.
For the moment, this is a application for the user on its Linux computer or who knows how to run it on a server.
There is not yet a mobile version, what I even would like to work on, so the design is mobile responsive on card design.
That's even one thing, how to make data beautiful visible from a table.
