### ISSUE TITLE
Docker, because it's effectively the universal package manager.

### ISSUE THREAD

**Issue by Leopere** [petrk94/ownhealthrecord#9]
I was thinking about contributing a [PR with Docker](https://github.com/Leopere/ownhealthrecord/tree/docker)

Is it possible to get full instructions for how you generate the releases and details about what you're using to run this?

If so I can convert the instructions into a multi stage docker container and potentially a Travis CI job that can build upload and release/test your git pushes.

This isn't high priority for me so it may take a while but the faster I get a response the more likely it will be that it can get done.

**Comment by pedrohenriquebr** [comment]
Hi, look at the `docker` branch. I'm using the Makefile for automating tasks.

[docker](https://github.com/pedrohenriquebr/ownhealthrecord/tree/docker).

maybe this can help...

**Comment by petrk94** [comment]
Hi guys, 

really nice what you are doing here about docker^^
I even would like to make a docker version, but it doesnt help, if there are more docker versions which might be not working properly or make problems etc.

I want to make a official docker compose file, if you modify something on it, please mention it on the readme file, otherwise it can be harmful.
Share here your ideas what you want to make for a docker stuff.

**Comment by Leopere** [comment]
One of the things that could be beneficial for a container that builds all branches via something like Travis CI would be you could build an entire test suite to ensure that your product is always effective.

**Comment by Leopere** [comment]
~~@pedrohenriquebr how should we go about using this Dockerfile and commit history you've added?  I would love to start with yours and then perhaps do a PR together.~~

I didn't see your PR on my fork I'll do a bit of work on it if @petrk94 is okay with the idea however it sounds like they want to do it all themselves.  

What  would recommend is that if @petrk94 wants to only have official releases be pushed to Docker Hub that they only build a specific branch and consider that branch only there for pushing docker releases.  A production branch would be ideal but there's heaps of ways to do it.

**Comment by petrk94** [comment]
@Leopere
Yes, please send me your docker file/ docker-compose and we can check it here together whether it's fine or what can be improved.

The reason why I want a official docker release on docker hub is, that I have seen already other projects where was different releases there and that's just a mess to find the one which is still maintained or at least working.

This Travis CI I never have made, so I have to get into it

**Comment by Leopere** [comment]
I have to learn Travis CI a bit more myself but I've done some work with it already.  You're welcomed to have a look at [my fork](https://github.com/Leopere/ownhealthrecord/blob/master/Dockerfile) to see what @pedrohenriquebr has done so far I started my stuff in my own fork but Pedro's fork has a lot more features than I would've imagined to do.  I also requested that he document how someone would use it.  

@pedrohenriquebr if you could use https://asciinema.org to record a quick "video" of how your Dockerfile docker-compose and Makefile's work it would be very interesting to see.

**Comment by pedrohenriquebr** [comment]
@Leopere I sent a message to you on Gitter

**Comment by petrk94** [comment]
@pedrohenriquebr if its related to the issue, please share it here too. Thanks

@Leopere if you have already a docker file we can test, just send me a PR I will test it and than we can merge

**Comment by pedrohenriquebr** [comment]
Here https://asciinema.org/a/222853

**Comment by Leopere** [comment]
So from your video @pedrohenriquebr I'm noticing one big glaring issue, I think that generally people these days prefer to have the database schema automatically created if its not there.  @petrk94 would you be opposed to writing something that would do this automatically when OHR is initialized?

**Comment by Leopere** [comment]
@pedrohenriquebr I love the makefile its very nice!  The only critique I would make is that when it comes down to Documentation we should favour using Docker commands because that makes the instructions more portable across operating systems.  Otherwise good job looks great to me!

**Comment by pedrohenriquebr** [comment]
@Leopere  Okay, I'm going to modify the Makefile

**Comment by petrk94** [comment]
@Leopere 
I had planned to use a php database framework so it will take over this work. But due there is encryption code inside, I have to test it when I have time.
So as next what is necessary, is to create the necessary tables for the database over the setup form at the beginning.

**Comment by Leopere** [comment]
@petrk94 https://www.slant.co/topics/5639/~php-orms might put you on the right path.

**Comment by petrk94** [comment]
@Leopere 
I have checked that out, but all of them looks more complicated.
Rather I think medoo is much more easier and provide the same functions we need to make the application usable for more than just one database model.

https://medoo.in / https://github.com/catfan/Medoo
